version: 2

jobs:
  macos:
    macos:
      xcode: "9.3.0"
    steps:
      - checkout
      - run: brew install libressl 
      - run: swift build
      - run: swift test
  linux:
    docker:
      - image: norionomura/swift:411
    steps:
      - checkout
      - run: swift build
      - run: swift test
workflows:
  version: 2
  tests:
    jobs:
      - linux
      # - macos
